version: "3.8"

services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring
    environment:
      SPRING_PROFILES_ACTIVE: dev
    ports:
      - "8080:8080"
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge