services:
  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    networks:
      - backend
networks:
  app-network:
    driver: bridge # 가장 일반적인 브릿지 네트워크 타입입니다.
