spring:
  datasource:
    url: jdbc:mysql://guyon-dev.cqsc6pyqhwww.ap-northeast-2.rds.amazonaws.com:3306/mydb?sslMode=REQUIRED&serverTimezone=Asia/Seoul
    username: guyon
    password: 5T=f=Zd=DhtT.(ozj4o&-i(}LNQ

weather-api:
  secret-key: