spring:
  datasource:
    url: jdbc:h2:mem:lv3;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  jpa:
    hibernate.ddl-auto: create-drop

spring.h2.console.enabled: true
spring.h2.console.path: /h2-console