spring:
  application:
    name: lv3-final-mission
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

weather-api:
  secret-key: