name: CI - Test - PR

on:
  pull_request:
    branches: [ dev ]
    types: [ opened, synchronize ]

concurrency:
  group: ci-test-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'

      - name: Run tests
        run: ./gradlew test --stacktrace
